from enum import Enum, IntFlag

import v4l2.uapi

__all__ = [ 'MediaEntityFunction', 'MediaLinkFlag', 'MediaPadFlag', 'MediaInterfaceType' ]

class MediaEntityFunction(Enum):
    UNKNOWN = v4l2.uapi.MEDIA_ENT_F_UNKNOWN
    V4L2_SUBDEV_UNKNOWN = v4l2.uapi.MEDIA_ENT_F_V4L2_SUBDEV_UNKNOWN
    DTV_DEMOD = v4l2.uapi.MEDIA_ENT_F_DTV_DEMOD
    TS_DEMUX = v4l2.uapi.MEDIA_ENT_F_TS_DEMUX
    DTV_CA = v4l2.uapi.MEDIA_ENT_F_DTV_CA
    DTV_NET_DECAP = v4l2.uapi.MEDIA_ENT_F_DTV_NET_DECAP
    IO_V4L = v4l2.uapi.MEDIA_ENT_F_IO_V4L
    IO_DTV = v4l2.uapi.MEDIA_ENT_F_IO_DTV
    IO_VBI = v4l2.uapi.MEDIA_ENT_F_IO_VBI
    IO_SWRADIO = v4l2.uapi.MEDIA_ENT_F_IO_SWRADIO
    CAM_SENSOR = v4l2.uapi.MEDIA_ENT_F_CAM_SENSOR
    FLASH = v4l2.uapi.MEDIA_ENT_F_FLASH
    LENS = v4l2.uapi.MEDIA_ENT_F_LENS
    TUNER = v4l2.uapi.MEDIA_ENT_F_TUNER
    IF_VID_DECODER = v4l2.uapi.MEDIA_ENT_F_IF_VID_DECODER
    IF_AUD_DECODER = v4l2.uapi.MEDIA_ENT_F_IF_AUD_DECODER
    AUDIO_CAPTURE = v4l2.uapi.MEDIA_ENT_F_AUDIO_CAPTURE
    AUDIO_PLAYBACK = v4l2.uapi.MEDIA_ENT_F_AUDIO_PLAYBACK
    AUDIO_MIXER = v4l2.uapi.MEDIA_ENT_F_AUDIO_MIXER
    PROC_VIDEO_COMPOSER = v4l2.uapi.MEDIA_ENT_F_PROC_VIDEO_COMPOSER
    PROC_VIDEO_PIXEL_FORMATTER = v4l2.uapi.MEDIA_ENT_F_PROC_VIDEO_PIXEL_FORMATTER
    PROC_VIDEO_PIXEL_ENC_CONV = v4l2.uapi.MEDIA_ENT_F_PROC_VIDEO_PIXEL_ENC_CONV
    PROC_VIDEO_LUT = v4l2.uapi.MEDIA_ENT_F_PROC_VIDEO_LUT
    PROC_VIDEO_SCALER = v4l2.uapi.MEDIA_ENT_F_PROC_VIDEO_SCALER
    PROC_VIDEO_STATISTICS = v4l2.uapi.MEDIA_ENT_F_PROC_VIDEO_STATISTICS
    PROC_VIDEO_ENCODER = v4l2.uapi.MEDIA_ENT_F_PROC_VIDEO_ENCODER
    PROC_VIDEO_DECODER = v4l2.uapi.MEDIA_ENT_F_PROC_VIDEO_DECODER
    PROC_VIDEO_ISP = v4l2.uapi.MEDIA_ENT_F_PROC_VIDEO_ISP
    VID_MUX = v4l2.uapi.MEDIA_ENT_F_VID_MUX
    VID_IF_BRIDGE = v4l2.uapi.MEDIA_ENT_F_VID_IF_BRIDGE
    ATV_DECODER = v4l2.uapi.MEDIA_ENT_F_ATV_DECODER
    DV_DECODER = v4l2.uapi.MEDIA_ENT_F_DV_DECODER
    DV_ENCODER = v4l2.uapi.MEDIA_ENT_F_DV_ENCODER

class MediaLinkFlag(IntFlag):
    ENABLED = v4l2.uapi.MEDIA_LNK_FL_ENABLED
    IMMUTABLE = v4l2.uapi.MEDIA_LNK_FL_IMMUTABLE
    DYNAMIC = v4l2.uapi.MEDIA_LNK_FL_DYNAMIC

class MediaPadFlag(IntFlag):
    SINK = v4l2.uapi.MEDIA_PAD_FL_SINK
    SOURCE = v4l2.uapi.MEDIA_PAD_FL_SOURCE
    MUST_CONNECT = v4l2.uapi.MEDIA_PAD_FL_MUST_CONNECT
    INTERNAL = v4l2.uapi.MEDIA_PAD_FL_INTERNAL

class MediaInterfaceType(Enum):
    DVB_FE = v4l2.uapi.MEDIA_INTF_T_DVB_FE
    DVB_DEMUX = v4l2.uapi.MEDIA_INTF_T_DVB_DEMUX
    DVB_DVR = v4l2.uapi.MEDIA_INTF_T_DVB_DVR
    DVB_CA = v4l2.uapi.MEDIA_INTF_T_DVB_CA
    DVB_NET = v4l2.uapi.MEDIA_INTF_T_DVB_NET
    V4L_VIDEO = v4l2.uapi.MEDIA_INTF_T_V4L_VIDEO
    V4L_VBI = v4l2.uapi.MEDIA_INTF_T_V4L_VBI
    V4L_RADIO = v4l2.uapi.MEDIA_INTF_T_V4L_RADIO
    V4L_SUBDEV = v4l2.uapi.MEDIA_INTF_T_V4L_SUBDEV
    V4L_SWRADIO = v4l2.uapi.MEDIA_INTF_T_V4L_SWRADIO
    V4L_TOUCH = v4l2.uapi.MEDIA_INTF_T_V4L_TOUCH
    ALSA_BASE = v4l2.uapi.MEDIA_INTF_T_ALSA_BASE
    ALSA_PCM_CAPTURE = v4l2.uapi.MEDIA_INTF_T_ALSA_PCM_CAPTURE
    ALSA_PCM_PLAYBACK = v4l2.uapi.MEDIA_INTF_T_ALSA_PCM_PLAYBACK
    ALSA_CONTROL = v4l2.uapi.MEDIA_INTF_T_ALSA_CONTROL
